Repository 2025-HELLO/HELLO-FE, pull requests merged in 2025-08, with the labels that each got.

#8 Feat: 디자인 토큰 추가
  src/main.tsx
  src/styles/token/color.css.ts
  src/styles/token/typography.css.ts
Labels: ⚙️ Setting, 🐵 지수

#11 Feat: 회원가입 페이지 퍼블리싱
  .svgrrc.json
  public/svgs/ic_back.svg
  src/App.tsx
  src/assets/svgs/IcBack.tsx
  src/assets/svgs/index.ts
  src/common/components/button/Button.css.ts
  src/common/components/button/Button.tsx
  src/common/components/header/Header.css.ts
  src/common/components/header/Header.tsx
  src/common/components/header/PageHeader.css.ts
  src/common/components/header/PageHeader.tsx
  src/common/components/progress/SignupProgress.css.ts
  src/common/components/progress/SignupProgress.tsx
  src/main.tsx
  src/pages/signup/hooks/useSignupProgress.ts
  src/pages/signup/page/Signup.css.ts
  src/pages/signup/page/Signup.tsx
  src/pages/signup/page/step/AccountStep.css.ts
  src/pages/signup/page/step/AccountStep.tsx
  src/pages/signup/page/step/CompleteStep.css.ts
  src/pages/signup/page/step/CompleteStep.tsx
  src/pages/signup/page/step/TermsStep.css.ts
  src/pages/signup/page/step/TermsStep.tsx
  src/pages/signup/page/step/VerifyStep.css.ts
  src/pages/signup/page/step/VerifyStep.tsx
  src/shared/components/layout/Layout.tsx
  src/shared/constants/path.ts
  src/shared/routes/MainRoutes.tsx
  src/styles/global.css.ts
  src/styles/token/color.css.ts
  src/styles/token/index.ts
  src/styles/token/layout.css.ts
  src/styles/token/typography.css.ts
Labels: ✨ Feature, 🐵 지수

#16 Feat: 홈화면 UI 구현
  src/pages/home/page/Home.css.ts
  src/pages/home/page/Home.tsx
Labels: ✨ Feature, 😺 서연

#23 Feat: 채팅화면 헤더 구현
  public/svgs/ic_hamburger.svg
  src/common/components/header/ChatHeader.tsx
  src/pages/chat/page/Chat.tsx
  src/pages/home/page/Home.tsx
  src/shared/constants/path.ts
  src/shared/routes/MainRoutes.tsx
Labels: ✨ Feature, 😺 서연

#24 Feat: 채팅 화면 UI 및 음성 입력 기능 구현
  public/svgs/ic_mic.svg
  public/svgs/ic_send.svg
  src/pages/chat/page/Chat.css.ts
  src/pages/chat/page/Chat.tsx
Labels: ✨ Feature, 😺 서연

#25 Feat: 채팅 입력창 및 버블 스타일 개선
  src/pages/chat/page/Chat.css.ts
  src/pages/chat/page/Chat.tsx
Labels: 🎨 Design, 😺 서연

#27 Feat: 채팅리스트 화면 구현
  public/svgs/ic_trash.svg
  src/common/components/header/ChatHeader.tsx
  src/pages/chat/page/ChatList.css.ts
  src/pages/chat/page/ChatList.tsx
  src/shared/constants/path.ts
  src/shared/routes/MainRoutes.tsx
Labels: ✨ Feature, 😺 서연
